# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = CleverClient
DESTDIR = ../x64/Release
CONFIG += release
LIBS += -L"." \
    -l/"$(INHERIT)/"
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(CleverClient.pri)
win32:RC_FILE = CleverClient.rc